[package]
name = 'ai_parser'
version = '0.1.0'
edition = '2018'

[dependencies]
chatgpt_rs = { version = "1.1.1", features = [] }
tokio = { version = "1.15", features = ["full"] }
futures = "0.3"


[[bin]]
name = 'ai_parser'
path = 'src/main.rs'
